name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck libcppunit-dev fakeroot dpkg-dev

    # Step 3: Run linting
    - name: Run lint
      run: make lint

    # Step 4: Run tests
    - name: Run tests
      run: make test

    # Step 5: Build the program
    - name: Build the program
      run: make build

    # Step 6: Package the program
    - name: Package the program
      run: make package
